### ISSUE TITLE
Installation error "No file found for given UID."

### ISSUE THREAD

**Issue by lampela** [maximilian-mayer/t3onepage#17]
"#1317178604: No file found for given UID. (More information)

TYPO3\CMS\Core\Resource\Exception\FileDoesNotExistException thrown in file
/var/www/vhosts/typo3_src-6.2.4/typo3/sysext/core/Classes/Resource/ResourceFactory.php in line 356"

TYPO3 6.2.4 and tried both latest TER version and git master version of t3onepage.

**Comment by mmasmoudi** [comment]
Hi, i have the same error, i used typo3 6.2.9 a fresh install and t3onepage package from extension manager. the extension is not activated but there is some page in the web tree. is there a solution.

**Comment by lampela** [comment]
SOLVED LIKE THIS: I deleted all the existing content elements containing images. That solved the problems and everything seem to work now :)

**Comment by mmasmoudi** [comment]
Thank you for the hints Iampela, i did that, but when i try to activate the extension after deleting the ce this error show up, do you have an idea  ?

**Comment by lampela** [comment]
If you have cleared all the references to old image elements and cleared the cache I don't what's wrong, for me that helped.

**Comment by mmasmoudi** [comment]
Thank you, but after clearing the images, i try to activate the t3onepage extension, it makes a new webpage tree that contains new CE with images. Maybe i did something wrong

**Comment by lampela** [comment]
Can't you delete the images after activating the extension agan? (sorry I don't remember the order in which I did the various things)

**Comment by helmut-winkelbach** [comment]
I did change to t3sbootstrap, see
http://www.t3sbootstrap.de/1/t3sbootstrap/

It has also a onepage solution
http://www.t3solution.de/

**Comment by DavidBruchmann** [comment]
All CEs with Text & Image can be left visible, there is only one CE with
Image only and that has to be disabled.
Disabling can be done either in the BE after ignoring some errormessages,
or by PHPmyAdmin in the table tt_content. There the element with the value
"image" in the col "CType" has to get the value 0 in the col "deleted", by
SQL you can do it with one line:

UPDATE `tt_content` SET `deleted` =
<http://localhost/phpmyadmin/url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.6%2Fen%2Fcomparison-operators.html%23operator_equal&token=74a781b715bf4618076dd183dc018d16>
'0' WHERE `CType` =
<http://localhost/phpmyadmin/url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.6%2Fen%2Fcomparison-operators.html%23operator_equal&token=74a781b715bf4618076dd183dc018d16>
"image";

Nevertheless any images in the other CEs are not shown and in the database
I never found any in the table tt_content.
To get the stylesheet installed automatically you should install the
extension from TER, as here on git the stylesheet is removed for some
reason I don't know.

On Wed, Jan 14, 2015 at 9:44 PM, helmut-winkelbach <notifications@github.com
