### ISSUE TITLE
Failed install on TYPO3 6.2.13/4

### ISSUE THREAD

**Issue by mario6097** [maximilian-mayer/t3onepage#21]
Hi

I am trying to install  (TYPO3 6.2.13, +) t3onepage distribution and I fail. 
I get to the Configure/View/start /Start to edit page, hence everything should be ok, but indeed the page tree is still empty. 
Is there anything I need to set or check?
Thanks Regards
mario

**Comment by maximilian-mayer** [comment]
hi @mario6097,
please import the data.t3d manually from extension root.
